"""Generate ablation experiment commands for DSTSANet.

This script does NOT execute training. It prints (and optionally saves) the
commands needed to run the ablation experiments comparing the original
DSTSANet encoder (different encoders for low/high frequency branches) against
two variants where both branches share the same encoder type.

Variants:
  - attn_shared: both branches use Temporal Attention (independent params)
  - conv_shared: both branches use Temporal Causal Conv (independent params)

Usage:
    python run_ablation.py                 # print commands to stdout
    python run_ablation.py --save FILE.sh  # also save commands to a shell script
    python run_ablation.py --execute       # actually run the commands sequentially
"""

import argparse
import os


# Default datasets to run ablation on. Modify this list to fit your data layout.
DEFAULT_DATASETS = [
    {
        'name': 'PeMSD3',
        'traffic_file': './data/PeMSD3/PeMSD3.npz',
        'adj_file': './data/PeMSD3/adj.npy',
        'tem_adj_file': './data/PeMSD3/tem_adj.npy',
        'model_file': './work_dirs/PeMSD3/PeMSD3.pth',
        'log_file': './log/PeMSD3/log_train.txt',
    },
    {
        'name': 'PeMSD4',
        'traffic_file': './data/PeMSD4/PeMSD4.npz',
        'adj_file': './data/PeMSD4/adj.npy',
        'tem_adj_file': './data/PeMSD4/tem_adj.npy',
        'model_file': './work_dirs/PeMSD4/PeMSD4.pth',
        'log_file': './log/PeMSD4/log_train.txt',
    },
    {
        'name': 'PeMSD7',
        'traffic_file': './data/PeMSD7/PeMSD7.npz',
        'adj_file': './data/PeMSD7/adj.npy',
        'tem_adj_file': './data/PeMSD7/tem_adj.npy',
        'model_file': './work_dirs/PeMSD7/PeMSD7.pth',
        'log_file': './log/PeMSD7/log_train.txt',
    },
    {
        'name': 'PeMSD8',
        'traffic_file': './data/PeMSD8/PeMSD8.npz',
        'adj_file': './data/PeMSD8/adj.npy',
        'tem_adj_file': './data/PeMSD8/tem_adj.npy',
        'model_file': './work_dirs/PeMSD8/PeMSD8.pth',
        'log_file': './log/PeMSD8/log_train.txt',
    },
]

ABLATION_MODES = ['attn_shared', 'conv_shared']


def build_command(dataset, ablation, seed=1, extra_overrides=None):
    """Build the shell command to run a single ablation experiment."""
    parts = [
        'python main.py',
        f'--seed {seed}',
        f'--traffic_file "{dataset["traffic_file"]}"',
        f'--adj_file "{dataset["adj_file"]}"',
        f'--tem_adj_file "{dataset["tem_adj_file"]}"',
        f'--model_file "{dataset["model_file"]}"',
        f'--log_file "{dataset["log_file"]}"',
        f'--ablation {ablation}',
    ]
    if extra_overrides:
        parts.extend(extra_overrides)
    # Tag model file name so different ablation runs don't overwrite each other
    parts[-2] = parts[-2].replace(
        os.path.basename(dataset['model_file']).replace('.pth', ''),
        f'{os.path.basename(dataset["model_file"]).replace(".pth", "")}_{ablation}'
    )
    return ' '.join(parts)


def main():
    parser = argparse.ArgumentParser(description='Generate DSTSANet ablation commands')
    parser.add_argument('--save', type=str, default=None,
                        help='If set, save commands to this shell script file')
    parser.add_argument('--execute', action='store_true',
                        help='Actually execute the generated commands sequentially')
    parser.add_argument('--datasets', type=str, nargs='+', default=None,
                        help='Subset of dataset names to run (default: all)')
    parser.add_argument('--seed', type=int, default=1, help='Random seed')
    args = parser.parse_args()

    datasets = DEFAULT_DATASETS
    if args.datasets:
        datasets = [d for d in DEFAULT_DATASETS if d['name'] in args.datasets]
        if not datasets:
            raise ValueError(f"No matching datasets. Available: {[d['name'] for d in DEFAULT_DATASETS]}")

    commands = []
    for ds in datasets:
        for mode in ABLATION_MODES:
            cmd = build_command(ds, mode, seed=args.seed)
            commands.append(cmd)
            print(cmd)

    if args.save:
        with open(args.save, 'w', encoding='utf-8') as f:
            f.write('#!/bin/bash\n')
            f.write('# DSTSANet ablation experiments\n')
            f.write('# Generated by run_ablation.py - DO NOT EDIT BY HAND\n\n')
            for cmd in commands:
                f.write(cmd + '\n')
        print(f'\nSaved {len(commands)} commands to {args.save}')

    if args.execute:
        import subprocess
        for cmd in commands:
            print(f'\n>>> Running: {cmd}')
            ret = subprocess.run(cmd, shell=True)
            if ret.returncode != 0:
                print(f'Command failed with exit code {ret.returncode}: {cmd}')
                break


if __name__ == '__main__':
    main()